# Generated by Django 3.1.7 on 2021-03-27 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='actual_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
